import { useState, useEffect, useRef } from 'react'
import { Link } from 'react-router-dom'
import '../styles/about.css'

function Typewriter({ text, delay = 100 }) {
  const [displayed, setDisplayed] = useState('')
  
  useEffect(() => {
    let i = 0
    const timer = setInterval(() => {
      setDisplayed(text.slice(0, i + 1))
      i++
      if (i >= text.length) clearInterval(timer)
    }, delay)
    return () => clearInterval(timer)
  }, [text, delay])
  
  return <>{displayed}<span className="typewriter-cursor">|</span></>
}

const journeySections = [
  { id: 'experience', label: 'Experience', cmd: 'cd experience' },
  { id: 'education', label: 'Education', cmd: 'cd education' },
  { id: 'hackathons', label: 'Hackathons', cmd: 'cd hackathons' },
  { id: 'certificates', label: 'Certificates', cmd: 'cd certificates' },
]

function About() {
  const sectionRefs = useRef([])

  // Scroll reveal for sections
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('revealed')
          }
        })
      },
      { threshold: 0.12 }
    )

    sectionRefs.current.forEach((el) => {
      if (el) observer.observe(el)
    })

    return () => observer.disconnect()
  }, [])

  const addToRefs = (el) => {
    if (el && !sectionRefs.current.includes(el)) {
      sectionRefs.current.push(el)
    }
  }

  const [activeJourney, setActiveJourney] = useState('experience')

  // Find the active section's command for the terminal title
  const activeCmd = journeySections.find(s => s.id === activeJourney)?.cmd || 'cd ~'

  return (
    <div className="about-page">
      {/* ═══════════════════════════════════════
          SECTION 1: HERO INTRO 
          ═══════════════════════════════════════ */}
      <section className="about-hero">
        <div className="about-hero-label">ABOUT</div>
        <div className="about-hero-row">
          <h1 className="about-hero-heading">
            Beyond<br />
            <span className="about-hero-accent">
              <Typewriter text="building" delay={120} />
            </span>
          </h1>
          <p className="about-hero-intro">
            I'm Hana Soummar, a Data Scientist and AI Engineer with an M.Sc. from INSEA, Morocco. 
            Driven by the belief that technology should do more than serve people, I build intelligent 
            systems that learn, evolve, and empower better decisions.
          </p>
        </div>
      </section>

      {/* ═══════════════════════════════════════
          SECTION 2: IMAGE + MY STORY
          ═══════════════════════════════════════ */}
      <section className="about-story" ref={addToRefs}>
        <div className="about-story-grid">
          <div className="about-story-image">
            <div className="about-story-image-frame">
              <img src="/assets/hana-portrait.png" alt="Hana Soummar" />
              <div className="about-story-image-glow" />
            </div>
            <div className="about-story-image-caption">
              <span className="about-story-caption-prompt">$</span> cat hana.profile
            </div>
          </div>

          <div className="about-story-content">
            <h2 className="about-story-title">What Drives Me?</h2>
            
            <p className="about-story-text">
              My journey into Artificial Intelligence began while developing an HR management application 
              as part of my undergraduate final project.
            </p>
            
            <p className="about-story-text">
              During the project presentation, after reviewing my work, one of the jury members asked 
              a question that completely changed the way I think about technology:
            </p>
            
            <blockquote className="about-story-quote">
              "Why build a static dashboard when the data generated by your HR application could be 
              leveraged through AI and data mining to uncover valuable insights and support smarter 
              decision-making?"
            </blockquote>
            
            <p className="about-story-text">
              That question stayed with me.
            </p>
            
            <p className="about-story-text">
              Until that moment, my focus had been on building applications that efficiently deliver 
              services. But I realized that technology should go beyond functionality. It should 
              <strong> learn, adapt, and help organizations make better decisions</strong>.
            </p>
            
            <p className="about-story-text">
              This experience reshaped my perspective and sparked my passion for 
              <span className="about-story-pink"> Artificial Intelligence</span> and 
              <span className="about-story-blue"> Data Science</span>. Since then, my mission has been 
              clear: to build intelligent systems that transform data into actionable insights, 
              anticipate future needs, and create meaningful impact.
            </p>

            {/* ─── Philosophy Cards — Terminal Style ─── */}
            <div className="about-story-philosophy">
              <div className="about-story-philosophy-header">
                <div className="about-story-philosophy-dot dot-pink" />
                <div className="about-story-philosophy-dot dot-blue" />
                <span className="about-story-philosophy-title">hana@portfolio: ~ $ cat values.md</span>
              </div>
              <div className="about-story-philosophy-body">
                <div className="about-story-philosophy-grid">
                  <div className="about-story-philosophy-card">
                    <div className="about-story-philosophy-cmd">
                      <span className="cmd-prompt">$</span>
                      <span className="cmd-text">npm run impact</span>
                    </div>
                    <div className="about-story-philosophy-number">01</div>
                    <h3 className="about-story-philosophy-card-title">Impact Over Hype</h3>
                    <p className="about-story-philosophy-desc">
                      I build AI that solves real problems. Every model, every pipeline, every dashboard 
                      must answer one question: <em>does this make someone's life better?</em>
                    </p>
                  </div>
                  <div className="about-story-philosophy-card">
                    <div className="about-story-philosophy-cmd">
                      <span className="cmd-prompt">$</span>
                      <span className="cmd-text">docker build systems</span>
                    </div>
                    <div className="about-story-philosophy-number">02</div>
                    <h3 className="about-story-philosophy-card-title">Systems Thinking</h3>
                    <p className="about-story-philosophy-desc">
                      A great model in a broken pipeline is worthless. I design end-to-end solutions — 
                      from data ingestion to deployment — that work reliably in production.
                    </p>
                  </div>
                  <div className="about-story-philosophy-card">
                    <div className="about-story-philosophy-cmd">
                      <span className="cmd-prompt">$</span>
                      <span className="cmd-text">git pull --evolve</span>
                    </div>
                    <div className="about-story-philosophy-number">03</div>
                    <h3 className="about-story-philosophy-card-title">Continuous Evolution</h3>
                    <p className="about-story-philosophy-desc">
                      AI moves fast. I move faster. Whether it's LoRA fine-tuning, vector databases, or 
                      the latest transformer architecture — I'm always building, always learning.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ═══════════════════════════════════════
          SECTION 3: MY JOURNEY — Terminal Nav + Content
          ═══════════════════════════════════════ */}
      <section className="about-journey-master" ref={addToRefs}>
        <div className="about-journey-master-header">
          <div className="about-journey-master-label">MY JOURNEY</div>
          <h2 className="about-journey-master-heading">
            My journey<br />
            <span className="about-journey-master-accent">at a glance</span>
          </h2>
        </div>

        <div className="journey-terminal">
          {/* ─── Terminal Header with Dot Navigation ─── */}
          <div className="journey-terminal-header">
            <div className="journey-terminal-dots">
              {journeySections.map((s) => (
                <button
                  key={s.id}
                  className={`journey-terminal-dot-btn ${activeJourney === s.id ? 'active' : ''}`}
                  onClick={() => setActiveJourney(s.id)}
                  aria-label={s.label}
                >
                  <span className="journey-terminal-dot-inner" />
                  <span className="journey-terminal-dot-label">{s.label}</span>
                </button>
              ))}
            </div>
            <span className="journey-terminal-title">
              hana@portfolio: ~ $ {activeCmd}
            </span>
          </div>

          {/* ─── Terminal Body — Content switches here ─── */}
          <div className="journey-terminal-body">
            {/* EXPERIENCE */}
            {activeJourney === 'experience' && (
              <div className="experience-list">
                <div className="experience-item">
                  <div className="experience-meta">
                    <span className="experience-date">Feb — Aug 2025</span>
                    <span className="experience-location">📍 Casablanca, Morocco</span>
                  </div>
                  <h3 className="experience-role">AI Research Assistant</h3>
                  <p className="experience-place">Oracle R&D Center</p>
                  <p className="experience-desc">
                    Built an enterprise semantic search system for automated support ticket grouping.
                    Used sentence embeddings, ChromaDB vector search, cross-encoder reranking —
                    deployed with FastAPI and React.js.
                  </p>
                  <div className="experience-tags">
                    <span className="experience-tag">NLP</span>
                    <span className="experience-tag">RAG</span>
                    <span className="experience-tag">FastAPI</span>
                    <span className="experience-tag">ChromaDB</span>
                    <span className="experience-tag">React</span>
                  </div>
                </div>

                <div className="experience-divider" />

                <div className="experience-item">
                  <div className="experience-meta">
                    <span className="experience-date">Jul — Sep 2024</span>
                    <span className="experience-location">📍 Morocco</span>
                  </div>
                  <h3 className="experience-role">AI Intern</h3>
                  <p className="experience-place">3D Smart Factory</p>
                  <p className="experience-desc">
                    3D Indoor Scene Segmentation using PyTorch, point cloud processing,
                    Weights & Biases, and Open3D.
                  </p>
                  <div className="experience-tags">
                    <span className="experience-tag">PyTorch</span>
                    <span className="experience-tag">Point Cloud</span>
                    <span className="experience-tag">Open3D</span>
                    <span className="experience-tag">W&B</span>
                  </div>
                </div>

                <div className="experience-divider" />

                <div className="experience-item">
                  <div className="experience-meta">
                    <span className="experience-date">Apr — Jun 2023</span>
                    <span className="experience-location">📍 Morocco</span>
                  </div>
                  <h3 className="experience-role">Web Development Intern</h3>
                  <p className="experience-place">Vala Orange</p>
                  <p className="experience-desc">
                    Full-stack HR Management system using Laravel with interactive dashboards.
                  </p>
                  <div className="experience-tags">
                    <span className="experience-tag">Laravel</span>
                    <span className="experience-tag">PHP</span>
                    <span className="experience-tag">MySQL</span>
                  </div>
                </div>
              </div>
            )}

            {/* EDUCATION */}
            {activeJourney === 'education' && (
              <div className="education-list">
                <div className="education-item">
                  <div className="education-meta">
                    <span className="education-date">2023 — 2025</span>
                    <span className="education-location">📍 Rabat, Morocco</span>
                  </div>
                  <h3 className="education-degree">Master — Information Systems & Intelligent Systems</h3>
                  <p className="education-school">INSEA Rabat</p>
                  <p className="education-desc">
                    Advanced AI, Machine Learning, Data Engineering, Business Intelligence
                  </p>
                </div>

                <div className="experience-divider" />

                <div className="education-item">
                  <div className="education-meta">
                    <span className="education-date">2022 — 2023</span>
                    <span className="education-location">📍 Settat, Morocco</span>
                  </div>
                  <h3 className="education-degree">Bachelor — Computer Science Engineering</h3>
                  <p className="education-school">FST Settat</p>
                  <div className="education-badges">
                    <span className="education-badge">Valedictorian</span>
                    <span className="education-badge">Honors</span>
                  </div>
                </div>

                <div className="experience-divider" />

                <div className="education-item">
                  <div className="education-meta">
                    <span className="education-date">2020 — 2022</span>
                    <span className="education-location">📍 Settat, Morocco</span>
                  </div>
                  <h3 className="education-degree">Undergraduate — Mathematics, Computer Science, Physics</h3>
                  <p className="education-school">FST Settat</p>
                  <div className="education-badges">
                    <span className="education-badge">Valedictorian</span>
                    <span className="education-badge">Honors</span>
                  </div>
                </div>

                <div className="experience-divider" />

                <div className="education-item">
                  <div className="education-meta">
                    <span className="education-date">2020</span>
                    <span className="education-location">📍 Inezgane, Morocco</span>
                  </div>
                  <h3 className="education-degree">High School Diploma — Mathematical Sciences</h3>
                  <p className="education-school">Lycée Houmman El Fetouaki-Inezgane</p>
                  <div className="education-badges">
                    <span className="education-badge">Honors</span>
                  </div>
                </div>
              </div>
            )}

            {/* HACKATHONS */}
            {activeJourney === 'hackathons' && (
              <div className="hackathon-card">
                <div className="hackathon-image">
                  <img src="/assets/oracle-hackathon.jpg" alt="Oracle SuiteBot AI Hackathon" />
                  <div className="hackathon-image-overlay">
                    <span className="hackathon-rank">🥈 2nd Place</span>
                  </div>
                </div>
                <div className="hackathon-content">
                  <div className="hackathon-meta">
                    <span className="hackathon-date">2025</span>
                    <span className="hackathon-location">📍 Oracle MADC, Morocco</span>
                  </div>
                  <h3 className="hackathon-title">Oracle SuiteBot AI Hackathon</h3>
                  <p className="hackathon-team">Team: Hana Soummar,Khawla Allak , Monsif Harchaoui</p>
                  
                  <p className="hackathon-desc">
                    A two-day challenge where we developed an AI bot in <strong>Java 21</strong> for a 
                    Tron-like competitive grid game. Our bot navigated in real-time, avoided collisions, 
                    and strategically took over space.
                  </p>

                  <div className="hackathon-highlights">
                    <div className="hackathon-highlight">
                      <span className="highlight-icon">✅</span>
                      <span>A bespoke <strong>Flood Fill algorithm</strong> to evaluate and take over free space</span>
                    </div>
                    <div className="hackathon-highlight">
                      <span className="highlight-icon">✅</span>
                      <span>A <strong>custom simulator</strong> built with JavaFX to visualize decision-making</span>
                    </div>
                  </div>

                  <p className="hackathon-reflection">
                    What made this experience truly valuable was seeing our theoretical knowledge 
                    translated into practical solutions. Each decision our bot made represented a 
                    trade-off between short-term survival and strategic long-term positioning — 
                    not unlike business decisions in real life.
                  </p>
                </div>
              </div>
            )}

            {/* CERTIFICATES */}
{activeJourney === 'certificates' && (
  <div className="certificates-grid">
    {[
      { name: 'Generative AI: Prompt Engineering Basics', issuer: 'IBM', date: 'Mar 2025' },
      { name: 'Generative AI for Everyone', issuer: 'DeepLearning.AI', date: 'Mar 2025' },
      { name: 'Git and GitHub', issuer: '365 Data Science', date: 'Nov 2024' },
      { name: 'Intermediate Python Programming', issuer: '365 Data Science', date: 'Nov 2024' },
      { name: 'Java', issuer: 'Sololearn', date: 'Jan 2023' },
      { name: 'Machine Learning', issuer: 'DeepLearning.AI', date: 'Oct 2024' },
      { name: 'Unsupervised Learning, Recommenders, RL', issuer: 'DeepLearning.AI', date: 'Oct 2024' },
      { name: 'Advanced Learning Algorithms', issuer: 'DeepLearning.AI', date: 'Oct 2024' },
      { name: 'Supervised ML: Regression & Classification', issuer: 'DeepLearning.AI', date: 'Aug 2024' },
      { name: 'Oracle AI Foundations', issuer: 'Oracle University', date: '2025' },
      { name: 'Deep Learning Specialization', issuer: 'DeepLearning.AI — Coursera', date: '2024' },
      { name: 'Machine Learning with Python', issuer: 'IBM — Coursera', date: '2024' },
      { name: 'Data Visualization with Tableau', issuer: 'UC Davis — Coursera', date: '2024' },
    ].map((cert, i) => (
      <a
        key={i}
        href="https://www.linkedin.com/in/hanasoummar/details/certifications/"
        target="_blank"
        rel="noopener noreferrer"
        className="certificate-card"
      >
        <div className="certificate-header">
          <span className="certificate-dot" />
          <span className="certificate-issuer">{cert.issuer}</span>
          <span className="certificate-date">{cert.date}</span>
        </div>
        <h3 className="certificate-name">{cert.name}</h3>
      </a>
    ))}
  </div>
)}
          </div>
        </div>
      </section>

      {/* ═══════════════════════════════════════
          SECTION 4: CTA
          ═══════════════════════════════════════ */}
      <section className="about-cta" ref={addToRefs}>
        <div className="about-cta-terminal">
          <div className="about-cta-terminal-header">
            <div className="about-cta-dot dot-pink" />
            <div className="about-cta-dot dot-blue" />
            <span className="about-cta-terminal-title">hana@portfolio: ~ $ ./connect.sh</span>
          </div>
          <div className="about-cta-terminal-body">
            <p className="about-cta-text">
              Want to know more about my work or discuss a project?
            </p>
            <div className="about-cta-actions">
              <Link to="/contact" className="about-cta-btn about-cta-primary">
                <span>[>_]</span> Start a conversation
                <span className="contact-action-arrow">→</span>
              </Link>
              
              <a href="/Resume_HANA_SOUMMAR.pdf" className="about-cta-btn about-cta-secondary" download>
                <span>📄</span> Download CV
                 <span className="contact-action-arrow">↗</span>
              </a>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}

export default About